# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1080Y4RXQudllZWJbkiD4MDU8yHXv_ZNy
"""



import pandas as pd

file_path = "enwiki_namespace_0_00000 (1).parquet"

df = pd.read_parquet(file_path)

print("Dataset loaded successfully!")
print("Rows and columns:", df.shape)

print("\nColumns:")
print(df.columns.tolist())

import os

print(os.listdir("/content"))

from google.colab import files

uploaded = files.upload()

import os

print(os.listdir("/content"))

# ==========================================
# WIKIQUIZ - COMPLETE PROTOTYPE
# ==========================================

import pandas as pd
import re
import random
import os

# 1. Load Wikimedia dataset
file_path = "/content/enwiki_namespace_0_00000 (1).parquet"

df = pd.read_parquet(file_path)

print("✅ Dataset loaded!")
print("Rows:", len(df))
print("Columns:", list(df.columns))


# 2. Find useful text columns automatically
text_columns = []

for col in df.columns:
    try:
        if df[col].dtype == "object":
            text_columns.append(col)
    except:
        pass

print("\nText columns found:")
print(text_columns)


# 3. Create searchable text
search_cols = []

for col in ["abstract", "description"]:
    if col in df.columns:
        search_cols.append(col)

if not search_cols:
    search_cols = text_columns[:3]

df["search_text"] = df[search_cols].fillna("").astype(str).agg(" ".join, axis=1)


# ==========================================
# SEARCH FUNCTION
# ==========================================

def search_topic(topic, n=5):

    topic = topic.lower().strip()

    result = df[
        df["search_text"].str.lower().str.contains(
            re.escape(topic),
            na=False
        )
    ]

    return result.head(n)


# ==========================================
# QUESTION GENERATION
# ==========================================

def make_questions(article, number=5):

    text_parts = []

    for col in search_cols:
        value = article.get(col, "")

        if pd.notna(value):
            text_parts.append(str(value))

    text = " ".join(text_parts)

    # Split into sentences
    sentences = re.split(r'(?<=[.!?])\s+', text)

    sentences = [
        s.strip()
        for s in sentences
        if len(s.strip()) > 40
    ]

    questions = []

    for sentence in sentences[:number]:

        words = re.findall(r'\b[A-Z][a-zA-Z]{3,}\b', sentence)

        if not words:
            continue

        answer = random.choice(words)

        question = sentence.replace(
            answer,
            "_____",
            1
        )

        # Create wrong answers from other words
        other_words = []

        for s in sentences:
            other_words += re.findall(
                r'\b[A-Z][a-zA-Z]{3,}\b',
                s
            )

        other_words = list(set(
            w for w in other_words
            if w != answer
        ))

        if len(other_words) < 3:
            continue

        options = random.sample(other_words, 3)
        options.append(answer)
        random.shuffle(options)

        questions.append({
            "question": question,
            "options": options,
            "answer": answer
        })

    return questions


# ==========================================
# RUN QUIZ
# ==========================================

topic = input("Enter a Wikipedia topic: ")

results = search_topic(topic)

if len(results) == 0:

    print("\n❌ No article found.")
    print("Try another topic such as:")
    print("India")
    print("Python")
    print("Computer")
    print("Technology")

else:

    print("\n✅ Article found!")

    article = results.iloc[0]

    print("\nArticle information:")

    for col in search_cols:
        print("\n", col, ":")
        print(article[col])

    questions = make_questions(article)

    print("\n\n========== WIKIQUIZ ==========\n")

    score = 0

    for i, q in enumerate(questions, 1):

        print(f"\nQ{i}. {q['question']}")

        for j, option in enumerate(q["options"]):
            print(f"{j+1}. {option}")

        try:
            choice = int(input("Your answer (1-4): "))
            selected = q["options"][choice-1]

            if selected == q["answer"]:
                print("✅ Correct!")
                score += 1
            else:
                print("❌ Wrong!")
                print("Correct answer:", q["answer"])

        except:
            print("Invalid answer.")

    print("\n==============================")
    print("FINAL SCORE:", score, "/", len(questions))
    print("==============================")

import gradio as gr

def wikiquiz_app(topic):

    results = search_topic(topic, 1)

    if len(results) == 0:
        return "❌ No article found. Try another topic.", ""

    article = results.iloc[0]

    questions = make_questions(article, 5)

    output = ""

    for i, q in enumerate(questions, 1):

        output += f"\nQ{i}. {q['question']}\n"

        for j, option in enumerate(q["options"], 1):
            output += f"{j}. {option}\n"

        output += f"Answer: {q['answer']}\n\n"

    return "✅ Quiz generated successfully!", output


demo = gr.Interface(
    fn=wikiquiz_app,
    inputs=gr.Textbox(
        label="Enter Wikipedia Topic",
        placeholder="Example: India"
    ),
    outputs=[
        gr.Textbox(label="Status"),
        gr.Textbox(label="Generated Quiz")
    ],
    title="📚 WikiQuiz",
    description="Generate a quiz from Wikimedia structured content"
)

demo.launch()

WikiQuiz.ipynb
